### ISSUE TITLE
IE下 fieldset自定义边框样式时，标题与边框重叠

### ISSUE THREAD

**Issue by cloudtian** [cloudtian/blogs#1]
problem: IE下 fieldset自定义边框样式时，标题与边框会出现重叠  
solution: 可通过设置legend的**background-color:#FFF**来修复  

![ie-fieldset](https://user-images.githubusercontent.com/13172526/50579582-35eff880-0e81-11e9-9cbe-9faa69799dfc.JPG)

```css
.fieldset {
    border: none;
    border-top: 1px dashed black;
    padding: 0;
}
.fieldset.solid {
    border-top: 1px solid black;
}
.title {
    background-color: #FFF;
}
```
```html
<fieldset class="fieldset solid">
    <legend>默认边框样式时；IE标题下与边框没有重叠</legend>
</fieldset>
<fieldset class="fieldset">
    <legend>自定义边框样式时；IE标题下与边框重叠</legend>
</fieldset>
<fieldset class="fieldset">
    <legend class="title">自定义边框时；IE标题下与边框重叠问题修复</legend>
</fieldset>
```
